In [ ]:
from dask.distributed import Client

client = Client(n_workers=5, threads_per_worker=3, memory_limit="15GB")
client

In [2]:
import dask.dataframe as dd

## 1. Newly Processed Data

In [4]:
df1 = dd.read_csv("data/raw/Lightcast_jobs_filtered_v3.csv")

In [5]:
df1

Dask DataFrame Structure:
                Unnamed: 0      ID START_DATE END_DATE COMPANY_NAME    ONET ONET_NAME NATION_RAW IS_CURRENT
npartitions=534
                     int64  string     string   string       string  string    string     string       bool
                       ...     ...        ...      ...          ...     ...       ...        ...        ...
...                    ...     ...        ...      ...          ...     ...       ...        ...        ...
                       ...     ...        ...      ...          ...     ...       ...        ...        ...
                       ...     ...        ...      ...          ...     ...       ...        ...        ...
Dask Name: read_csv, 1 expression
Expr=ReadCSV(ca027a3)

In [6]:
df1 = df1.iloc[:,1:].sort_values(by=['ID', 'START_DATE', 'IS_CURRENT'], ascending=[True, True, True])

In [7]:
df1 = df1.set_index("ID",inplace = True)

In [8]:
df1 = df1.persist()

2024-04-24 19:54:38,021 - tornado.application - ERROR - Uncaught exception GET /status/ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/status/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\ewp\AppData\Roaming\Python\Python312\site-packages\tornado\websocket.py", line 938, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ewp\AppData\Roaming\Python\Python312\site-packages\tornado\web.py", line 3301, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\bokeh\server\views\ws.py", line 149, in open
    raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired.
2024-04-24 19:57:09,132 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle b3a91813b669c7e44dc897f2999ceb21 initialized by task ('shuffle-transfer-b3a91813b669c7e44dc897f2999ceb21', 509) executed on worker tcp://127.0.0.1:58177
2024-04-24 20:07:37,397 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle b3a91813b669c7e44dc897f2999ceb21 deactivated due to stimulus 'task-finished-1714003657.3415918'
2024-04-24 20:07:45,814 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7440ffc77533d40ed729f7ef456c8fca initialized by task ('shuffle-transfer-7440ffc77533d40ed729f7ef456c8fca', 99) executed on worker tcp://127.0.0.1:58176
2024-04-24 20:17:57,028 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7440ffc77533d40ed729f7ef456c8fca deactivated due to stimulus 'task-finished-1714004276.797212'
2024-04-24 20:38:19,230 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle e6c6b911b88b741f7a72dad46f7964d3 initialized by task ('shuffle-transfer-e6c6b911b88b741f7a72dad46f7964d3', 533) executed on worker tcp://127.0.0.1:58173
Task exception was never retrieved
future: <Task finished name='Task-1534189' coro=<Client._gather.<locals>.wait() done, defined at c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\distributed\client.py:2197> exception=AllExit()>
Traceback (most recent call last):
  File "c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\distributed\client.py", line 2206, in wait
    raise AllExit()
distributed.client.AllExit
2024-04-24 20:42:25,141 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle e6c6b911b88b741f7a72dad46f7964d3 deactivated due to stimulus 'client-releases-keys-1714005745.13501'
2024-04-24 20:57:15,623 - distributed.scheduler - WARNING - Worker failed to heartbeat within 300 seconds. Closing: <WorkerState 'tcp://127.0.0.1:58173', name: 3, status: running, memory: 101, processing: 0>
2024-04-24 20:57:15,626 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:58173' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 431), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 440), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 504), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 449), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 513), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 458), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 522), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 467), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 531), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 433), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 497), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 442), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 506), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 451), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 515), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 460), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 524), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 469), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 533), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 490), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 435), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 499), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 444), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 508), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 453), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 517), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 526), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 483), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 428), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 492), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 437), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 501), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 446), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 510), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 455), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 519), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 476), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 485), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 494), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 439), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 503), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 512), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 478), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 487), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 432), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 496), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 441), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 505), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 450), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 514), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 471), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 480), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 489), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 498), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 443), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 507), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 464), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 528), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 473), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 482), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 491), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 436), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 500), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 457), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 521), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 466), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 530), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 475), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 484), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 493), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 459), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 523), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 468), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 532), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 477), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 486), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 495), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 452), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 516), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 461), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 525), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 470), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 479), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 488), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 445), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 509), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 454), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 518), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 463), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 527), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 472), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 481), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 438), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 502), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 447), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 511), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 456), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 520), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 465), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 529), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 474)} (stimulus_id='check-worker-ttl-1714006635.6236792')
2024-04-24 20:57:15,642 - distributed.scheduler - WARNING - Worker failed to heartbeat within 300 seconds. Closing: <WorkerState 'tcp://127.0.0.1:58177', name: 2, status: running, memory: 101, processing: 4>
2024-04-24 20:57:15,642 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:58177' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 111), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 175), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 120), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 193), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 138), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 83), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 202), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 147), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 211), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 168), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 177), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 186), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 131), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 195), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 140), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 161), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 170), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 115), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 179), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 124), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 188), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 133), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 197), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 462), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 163), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 53), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 172), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 117), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 126), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 190), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 199), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 156), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 165), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 174), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 119), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 183), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 128), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 192), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 149), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 213), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 167), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 176), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 121), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 185), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 142), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 206), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 151), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 160), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 169), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 114), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 425), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 144), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 208), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 153), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 162), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 281), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 171), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 409), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 180), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 18), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 137), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 201), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 146), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 210), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 164), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 173), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 130), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 194), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 139), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 203), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 148), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 212), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 157), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 166), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 123), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 187), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 13), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 196), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 141), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 205), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 150), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 159), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 116), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 125), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 189), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 134), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 198), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 317), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 143), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 207), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 152), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 118), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 182), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 127), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 191), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 17), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 136), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 200), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 145), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 209), ('operation-operation-sort_index-ec5b56d3bb720df94e174299b0686560', 154)} (stimulus_id='check-worker-ttl-1714006635.6236792')
2024-04-24 20:57:15,647 - distributed.scheduler - WARNING - Worker failed to heartbeat within 300 seconds. Closing: <WorkerState 'tcp://127.0.0.1:58185', name: 0, status: running, memory: 114, processing: 4>

In [9]:
df1.head(20)

,START_DATE,END_DATE,COMPANY_NAME,ONET,ONET_NAME,NATION_RAW,IS_CURRENT
ID,,,,,,,
----3D5YuLm98HP6nwwTLA_0000,2018-05-01,2021-01-01,Quad,99-9999.00,99-9999,united states,False
----3D5YuLm98HP6nwwTLA_0000,2021-05-01,2021-08-01,Agropur,99-9990,99-9999,canada,False
----3D5YuLm98HP6nwwTLA_0000,2021-08-01,2022-07-01,Agropur,15-1242.00,Database Administrators,canada,False
----3D5YuLm98HP6nwwTLA_0000,2022-05-01,2024-04-01,Agropur,13-1071.00,Human Resources Specialists,canada,True
----6yOZZQgiYKGQ2gwQ4Q_0000,2008-03-01,2011-11-01,Alius,27-1024.00,Graphic Designers,united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2009-11-01,2012-01-01,Hard Rock International,13-1121.00,"Meeting, Convention, and Event Planners",united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2012-03-01,2014-12-01,Lush,11-9199.00,"Managers, All Other",united kingdom,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2014-03-01,2020-12-01,MAC Cosmetics,11-9199.00,"Managers, All Other",united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2017-11-01,2020-12-01,MAC Cosmetics,25-3099.00,"Teachers and Instructors, All Other",united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2021-12-01,2024-04-01,Nordstrom,11-1021.00,General and Operations Managers,united states,True
----P-4JbZfsJdKWd6JA3w_0000,2007-01-01,2009-12-01,Metso,13-1161.00,Market Research Analysts and Marketing Special...,finland,False
----P-4JbZfsJdKWd6JA3w_0000,2012-03-01,2024-04-01,Metso,13-2011.00,Accountants and Auditors,finland,True
----PBMgg18ntD5KOEZd6A_0000,1975-08-01,2024-04-01,<NA>,21-1011.00,Substance Abuse and Behavioral Disorder Counse...,<NA>,True
----PBMgg18ntD5KOEZd6A_0000,2022-08-01,2022-08-01,Fwisd,25-2056.00,"Special Education Teachers, Elementary School",united states,False
---0BxJEA5u5989LaMkMbw_0000,2019-05-01,2019-11-01,<NA>,17-1011.00,"Architects, Except Landscape and Naval",<NA>,False
---0BxJEA5u5989LaMkMbw_0000,2021-06-01,2021-09-01,Vrisa Innovations Limited,99-9990,99-9999,india,False
---0BxJEA5u5989LaMkMbw_0000,2022-01-01,2022-06-01,<NA>,17-1011.00,"Architects, Except Landscape and Naval",<NA>,False
---0BxJEA5u5989LaMkMbw_0000,2023-05-01,2024-04-01,Next Step Ministries,47-1011.00,First-Line Supervisors of Construction Trades ...,united states,True
---0KdvEQZJHVrusyaBjfA_0000,2014-06-01,2017-04-01,Northern Illinois University,13-1151.00,Training and Development Specialists,united states,False
---0KdvEQZJHVrusyaBjfA_0000,2017-05-01,2018-10-01,Keypath Education,25-9031.00,Instructional Coordinators,united states,False

In [10]:
df1.to_parquet("Lightcast_jobs_filtered_sorted_V3.parquet")

## 2. Building transition matrix

In [3]:
import pandas as pd

In [4]:
df1 = dd.read_parquet("Lightcast_jobs_filtered_sorted_V3.parquet")

In [5]:
df1 = df1.set_index("ID",inplace = True)

In [6]:
df1

Dask DataFrame Structure:
                START_DATE END_DATE COMPANY_NAME    ONET ONET_NAME NATION_RAW IS_CURRENT
npartitions=534
                    string   string       string  string    string     string       bool
                       ...      ...          ...     ...       ...        ...        ...
...                    ...      ...          ...     ...       ...        ...        ...
                       ...      ...          ...     ...       ...        ...        ...
                       ...      ...          ...     ...       ...        ...        ...
Dask Name: read_parquet, 1 expression
Expr=ReadParquetFSSpec(af76935)

In [7]:
df1.head(15)

,START_DATE,END_DATE,COMPANY_NAME,ONET,ONET_NAME,NATION_RAW,IS_CURRENT
ID,,,,,,,
----3D5YuLm98HP6nwwTLA_0000,2018-05-01,2021-01-01,Quad,99-9999.00,99-9999,united states,False
----3D5YuLm98HP6nwwTLA_0000,2021-05-01,2021-08-01,Agropur,99-9990,99-9999,canada,False
----3D5YuLm98HP6nwwTLA_0000,2021-08-01,2022-07-01,Agropur,15-1242.00,Database Administrators,canada,False
----3D5YuLm98HP6nwwTLA_0000,2022-05-01,2024-04-01,Agropur,13-1071.00,Human Resources Specialists,canada,True
----6yOZZQgiYKGQ2gwQ4Q_0000,2008-03-01,2011-11-01,Alius,27-1024.00,Graphic Designers,united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2009-11-01,2012-01-01,Hard Rock International,13-1121.00,"Meeting, Convention, and Event Planners",united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2012-03-01,2014-12-01,Lush,11-9199.00,"Managers, All Other",united kingdom,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2014-03-01,2020-12-01,MAC Cosmetics,11-9199.00,"Managers, All Other",united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2017-11-01,2020-12-01,MAC Cosmetics,25-3099.00,"Teachers and Instructors, All Other",united states,False
----6yOZZQgiYKGQ2gwQ4Q_0000,2021-12-01,2024-04-01,Nordstrom,11-1021.00,General and Operations Managers,united states,True
----P-4JbZfsJdKWd6JA3w_0000,2007-01-01,2009-12-01,Metso,13-1161.00,Market Research Analysts and Marketing Special...,finland,False
----P-4JbZfsJdKWd6JA3w_0000,2012-03-01,2024-04-01,Metso,13-2011.00,Accountants and Auditors,finland,True
----PBMgg18ntD5KOEZd6A_0000,1975-08-01,2024-04-01,<NA>,21-1011.00,Substance Abuse and Behavioral Disorder Counse...,<NA>,True
----PBMgg18ntD5KOEZd6A_0000,2022-08-01,2022-08-01,Fwisd,25-2056.00,"Special Education Teachers, Elementary School",united states,False
---0BxJEA5u5989LaMkMbw_0000,2019-05-01,2019-11-01,<NA>,17-1011.00,"Architects, Except Landscape and Naval",<NA>,False

In [8]:
job_hop_count_df = pd.read_csv("data/raw/job_hop_count_empty.csv",index_col=0)

In [9]:
def custom_function(group):
    # Update list
    updates = []

    #group = group.repartition(npartitions=min(10, len(group)))

    group = group.reset_index(drop=True)  # Reset index without adding 'index' column
    
    for i in range(len(group) - 1):

        # Extract current job info
        current_st = group.loc[i, "START_DATE"]
        current_end = group.loc[i, "END_DATE"]
        current_ONET = group.loc[i, "ONET"]

        # Iterate through remaining experiences
        for j in range(i + 1, len(group)):  
            next_st = group.loc[j, "START_DATE"]
            #next_ONET = group.loc[j, "ONET"]
            
            # Check for overlap
            if next_st > current_st and next_st < current_end:
                # If there's overlap, handle as needed
                # Update your job_hop_count_df here based on your logic
                # Ensure this DataFrame is accessible and modifiable as intended
                #job_hop_count_df.loc[current_ONET][next_ONET] += 1
                update_info = {
                    'current_ONET': current_ONET,  # The ONET code of the current job experience
                    'next_ONET': group.loc[i+1, "ONET"],  # The ONET code of the next or overlapping job
                    'update_value': 1  # Assuming a simple count increment for each hop
                }
                updates.append(update_info)

            # If the first comparison after the current job doesn't overlap, break the loop
            if j == i + 1 and not (next_st > current_st and next_st < current_end):      # For variant where we count the extra hop to the next occupation without an overlap, we would change this line (exclude j==i+1)
                #job_hop_count_df.loc[current_ONET][next_ONET] += 1
                update_info = {'current_ONET': current_ONET,  
                            'next_ONET': group.loc[i+1, "ONET"],
                            'update_value': 1}
                updates.append(update_info)
                break
    
    return pd.DataFrame(updates)

    # Return modified group if necessary or perform other operations
    #return group  # Or update global DataFrame directly if that's your intent

# Example of how to apply custom_function to each group in a Dask DataFrame, assuming 'ID' is your groupby column
# Note: This pseudocode assumes job_hop_count_df is properly initialized and accessible within custom_function
# results = ddf.groupby('ID').apply(custom_function, meta=ddf).compute()  # Adjust 'meta' as necessary

In [10]:
result = df1.groupby('ID').apply(custom_function, meta={'current_ONET': 'object', 'next_ONET': 'object', 'update_value': 'int'})

In [14]:
# Assuming ddf is your Dask DataFrame
aggregated_ddf = result.groupby(['current_ONET', 'next_ONET']).agg({'update_value': 'sum'}).reset_index()

In [17]:
aggregated_ddf1 = aggregated_ddf.compute()

In [18]:
aggregated_ddf1

      current_ONET   next_ONET  update_value
0       43-1011.00  13-1111.00         63342
1       11-1011.00  11-9032.00         59376
2       37-3011.00  43-5071.00           553
3       41-1011.00  41-2031.00         43480
4       27-3041.00  11-2021.00         23375
...            ...         ...           ...
17552   11-3021.00  53-4041.00             1
17553   51-9041.00  51-9162.00             1
17554   13-2099.01  51-4081.00             1
17555   47-2043.00  11-9151.00             2
17556   11-3051.00  29-1128.00             1

[575306 rows x 3 columns]

In [20]:
aggregated_ddf1.to_parquet("Transitions_V2.parquet")

In [19]:
aggregated_ddf1.to_csv("Transitions_V2.csv")

In [21]:
aggregated_ddf1[(aggregated_ddf1.current_ONET == '11-1011.00') & (aggregated_ddf1.next_ONET == '11-1011.00')]

  current_ONET   next_ONET  update_value
6   11-1011.00  11-1011.00       1671109

In [22]:
piv = aggregated_ddf1.pivot_table(index='current_ONET', columns='next_ONET', values='update_value', fill_value=0)

In [23]:
piv

next_ONET,11-1011.00,11-1011.03,11-1021.00,11-1031.00,11-2011.00,11-2021.00,11-2022.00,11-2032.00,11-2033.00,11-3012.00,...,55-3011.00,55-3012.00,55-3013.00,55-3014.00,55-3015.00,55-3016.00,55-3018.00,55-3019.00,99-9990,99-9999.00
current_ONET,,,,,,,,,,,,,,,,,,,,,
11-1011.00,1671109.0,231.0,419847.0,3610.0,13555.0,201722.0,208864.0,100646.0,1543.0,8869.0,...,0.0,7.0,0.0,55.0,93.0,492.0,0.0,207.0,403802.0,157726.0
11-1011.03,228.0,275.0,114.0,1.0,2.0,113.0,58.0,129.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,225.0,53.0
11-1021.00,490682.0,159.0,1267475.0,893.0,7150.0,208434.0,302061.0,39268.0,499.0,12771.0,...,0.0,10.0,0.0,45.0,69.0,556.0,0.0,195.0,156934.0,69691.0
11-1031.00,2956.0,0.0,532.0,360.0,39.0,328.0,339.0,627.0,14.0,45.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3033.0,464.0
11-2011.00,17037.0,7.0,9598.0,52.0,25166.0,41604.0,16806.0,12102.0,108.0,337.0,...,0.0,0.0,0.0,0.0,6.0,4.0,0.0,7.0,16921.0,3147.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55-3016.00,2349.0,0.0,2830.0,8.0,19.0,576.0,1016.0,180.0,0.0,80.0,...,0.0,0.0,0.0,60.0,37.0,3663.0,0.0,158.0,6657.0,1676.0
55-3018.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55-3019.00,513.0,0.0,509.0,0.0,5.0,118.0,172.0,43.0,1.0,9.0,...,0.0,0.0,0.0,4.0,14.0,86.0,0.0,340.0,928.0,239.0
99-9990,287359.0,185.0,134896.0,2032.0,16303.0,138665.0,79466.0,76419.0,1798.0,5682.0,...,0.0,19.0,0.0,143.0,185.0,2287.0,0.0,592.0,3607929.0,272853.0
99-9999.00,191422.0,84.0,68210.0,627.0,3054.0,53575.0,33903.0,24739.0,490.0,2039.0,...,3.0,7.0,0.0,38.0,52.0,827.0,0.0,94.0,236303.0,519001.0

In [24]:
# Ensure the matrix is square
all_labels = piv.index.union(job_hop_count_df.index)
pivot_table = piv.reindex(index=all_labels, columns=all_labels, fill_value=0)

In [25]:
pivot_table

,11-1011.00,11-1011.03,11-1021.00,11-1031.00,11-2011.00,11-2021.00,11-2022.00,11-2032.00,11-2033.00,11-3012.00,...,55-3011.00,55-3012.00,55-3013.00,55-3014.00,55-3015.00,55-3016.00,55-3018.00,55-3019.00,99-9990,99-9999.00
11-1011.00,1671109.0,231.0,419847.0,3610.0,13555.0,201722.0,208864.0,100646.0,1543.0,8869.0,...,0.0,7.0,0.0,55.0,93.0,492.0,0.0,207.0,403802.0,157726.0
11-1011.03,228.0,275.0,114.0,1.0,2.0,113.0,58.0,129.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,225.0,53.0
11-1021.00,490682.0,159.0,1267475.0,893.0,7150.0,208434.0,302061.0,39268.0,499.0,12771.0,...,0.0,10.0,0.0,45.0,69.0,556.0,0.0,195.0,156934.0,69691.0
11-1031.00,2956.0,0.0,532.0,360.0,39.0,328.0,339.0,627.0,14.0,45.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3033.0,464.0
11-2011.00,17037.0,7.0,9598.0,52.0,25166.0,41604.0,16806.0,12102.0,108.0,337.0,...,0.0,0.0,0.0,0.0,6.0,4.0,0.0,7.0,16921.0,3147.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55-3016.00,2349.0,0.0,2830.0,8.0,19.0,576.0,1016.0,180.0,0.0,80.0,...,0.0,0.0,0.0,60.0,37.0,3663.0,0.0,158.0,6657.0,1676.0
55-3018.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55-3019.00,513.0,0.0,509.0,0.0,5.0,118.0,172.0,43.0,1.0,9.0,...,0.0,0.0,0.0,4.0,14.0,86.0,0.0,340.0,928.0,239.0
99-9990,287359.0,185.0,134896.0,2032.0,16303.0,138665.0,79466.0,76419.0,1798.0,5682.0,...,0.0,19.0,0.0,143.0,185.0,2287.0,0.0,592.0,3607929.0,272853.0
99-9999.00,191422.0,84.0,68210.0,627.0,3054.0,53575.0,33903.0,24739.0,490.0,2039.0,...,3.0,7.0,0.0,38.0,52.0,827.0,0.0,94.0,236303.0,519001.0

In [26]:
pivot_table.to_csv("Transition_Matrix_V2.csv")

In [28]:
import numpy as np

In [29]:
trans_prob = pivot_table.div(pivot_table.sum(axis = 1), axis=0).replace(np.nan, 0)

In [30]:
trans_prob

,11-1011.00,11-1011.03,11-1021.00,11-1031.00,11-2011.00,11-2021.00,11-2022.00,11-2032.00,11-2033.00,11-3012.00,...,55-3011.00,55-3012.00,55-3013.00,55-3014.00,55-3015.00,55-3016.00,55-3018.00,55-3019.00,99-9990,99-9999.00
11-1011.00,0.226798,0.000031,0.056981,0.000490,0.001840,0.027377,0.028346,0.013659,0.000209,0.001204,...,0.000000e+00,9.500212e-07,0.0,0.000007,0.000013,0.000067,0.0,0.000028,0.054803,0.021406
11-1011.03,0.068141,0.082188,0.034071,0.000299,0.000598,0.033772,0.017334,0.038553,0.000000,0.002092,...,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.067244,0.015840
11-1021.00,0.081444,0.000026,0.210378,0.000148,0.001187,0.034596,0.050137,0.006518,0.000083,0.002120,...,0.000000e+00,1.659819e-06,0.0,0.000007,0.000011,0.000092,0.0,0.000032,0.026048,0.011567
11-1031.00,0.125793,0.000000,0.022639,0.015320,0.001660,0.013958,0.014426,0.026682,0.000596,0.001915,...,0.000000e+00,0.000000e+00,0.0,0.000000,0.000043,0.000043,0.0,0.000000,0.129069,0.019746
11-2011.00,0.051591,0.000021,0.029064,0.000157,0.076206,0.125983,0.050891,0.036647,0.000327,0.001020,...,0.000000e+00,0.000000e+00,0.0,0.000000,0.000018,0.000012,0.0,0.000021,0.051239,0.009530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55-3016.00,0.018834,0.000000,0.022691,0.000064,0.000152,0.004618,0.008146,0.001443,0.000000,0.000641,...,0.000000e+00,0.000000e+00,0.0,0.000481,0.000297,0.029370,0.0,0.001267,0.053376,0.013438
55-3018.00,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
55-3019.00,0.027385,0.000000,0.027171,0.000000,0.000267,0.006299,0.009182,0.002295,0.000053,0.000480,...,0.000000e+00,0.000000e+00,0.0,0.000214,0.000747,0.004591,0.0,0.018150,0.049538,0.012758
99-9990,0.019885,0.000013,0.009335,0.000141,0.001128,0.009595,0.005499,0.005288,0.000124,0.000393,...,0.000000e+00,1.314775e-06,0.0,0.000010,0.000013,0.000158,0.0,0.000041,0.249664,0.018881
99-9999.00,0.051893,0.000023,0.018491,0.000170,0.000828,0.014524,0.009191,0.006706,0.000133,0.000553,...,8.132702e-07,1.897630e-06,0.0,0.000010,0.000014,0.000224,0.0,0.000025,0.064059,0.140696

In [32]:
trans_prob.to_csv("data/Transition_Probab_Matrix_V2.csv")

In [31]:
trans_prob.sum(axis=1)

11-1011.00    1.0
11-1011.03    1.0
11-1021.00    1.0
11-1031.00    1.0
11-2011.00    1.0
             ...
55-3016.00    1.0
55-3018.00    1.0
55-3019.00    1.0
99-9990       1.0
99-9999.00    1.0
Length: 1018, dtype: float64